export const BANK_LOGOS: Record<string, string> = {
  sbi:          '/banks/sbi.svg',
  hdfc:         '/banks/hdfc.svg',
  icici:        '/banks/icici.svg',
  axis:         '/banks/axis.svg',
  kotak:        '/banks/kotak.svg',
  pnb:          '/banks/pnb.svg',
  bob:          '/banks/bob.svg',
  canara:       '/banks/canara.svg',
  union:        '/banks/union.svg',
  indusind:     '/banks/indusind.svg',
  'idfc-first': '/banks/idfc-first.svg',
  yes:          '/banks/yes.svg',
  bajaj:        '/banks/bajaj.svg',
  boi:          '/banks/boi.svg',
  indian:       '/banks/indian.svg',
  central:      '/banks/central.svg',
  bom:          '/banks/bom.svg',
  federal:      '/banks/federal.svg',
  tata:         '/banks/tata.svg',
  'lic-housing': '/banks/lic-housing.svg',
  abc:          '/banks/abc.svg',
};
