import type { Metadata } from 'next';
import Image from 'next/image';
import React from 'react';
import Link from 'next/link';
import AdSlot from '@/components/AdSlot';
import WikiText from '@/components/WikiText';
import BreadcrumbJsonLd from '@/components/BreadcrumbJsonLd';
import ShareTools from '@/components/ShareTools';
import AuthorBio from '@/components/AuthorBio';
import InlineSipCalculator from '@/components/InlineSipCalculator';
import FAQSchema from '@/components/FAQSchema';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Badge } from '@/components/ui/badge';
import {
  Target,
  TrendingUp,
  Clock,
  Calculator,
  AlertTriangle,
  Lightbulb,
  CheckCircle2,
  PieChart,
  ArrowRight,
  Zap,
} from 'lucide-react';

// --- SEO METADATA ---
export const metadata: Metadata = {
  title: 'How much SIP for 1 Crore in 20 Years? (2025 Guide)',
  description:
    'Want to build ₹1 Crore wealth in 20 years? See the exact monthly SIP required (₹10,009), step-up strategy, and how compounding pays 75% of your goal.',
  keywords: [
    'SIP for 1 crore in 20 years',
    '1 crore sip calculator',
    'monthly investment for 1 crore',
    'long term wealth creation',
    'compounding effect calculator',
  ],
  twitter: {
    card: 'summary_large_image',
    title: 'How much SIP is needed for ₹1 Crore in 20 Years?',
    description: 'Wealth on Autopilot: The ₹10k/month strategy.',
    images: [
      'https://www.fincado.com/images/guides/mf/mutual-fund-guide-hero.webp',
    ],
  },
  alternates: {
    canonical: 'https://www.fincado.com/guides/sip-for-1-crore-in-20-years',
  },
  openGraph: {
    title: 'How much SIP for 1 Crore in 20 Years? (2025 Guide)',
    description:
      'Detailed breakdown: Monthly SIP needed, Step-up strategy, and Asset allocation to hit ₹1 Crore.',
    url: 'https://www.fincado.com/guides/sip-for-1-crore-in-20-years',
    type: 'article',
    images: [
      {
        url: 'https://www.fincado.com/images/guides/mf/mutual-fund-guide-hero.webp',
        width: 1200,
        height: 600,
        alt: 'Roadmap to 1 Crore Wealth in 20 Years',
      },
    ],
  },
};

export default function Sip1Cr20YearsPage() {
  const pageTitle = 'How much SIP is needed for ₹1 Crore in 20 Years?';

  const faqData = [
    {
      question: 'Is ₹1 crore realistic in 20 years via SIP?',
      answer:
        'Yes, it is extremely realistic. With a 20-year horizon, you only need to invest roughly ₹10,000/month. The power of compounding does 75% of the work for you.',
    },
    {
      question: 'What return rate is safe to assume for 20 years?',
      answer:
        'A 12% CAGR is a standard, conservative estimate for diversified Equity Mutual Funds over a long term like 20 years. This accounts for market ups and downs.',
    },
    {
      question: 'How much of the ₹1 Crore comes from my pocket?',
      answer:
        'Only about ₹24 Lakhs! The remaining ₹76 Lakhs is purely earnings/returns generated by the market. This is why starting early is called "Wealth on Autopilot".',
    },
    {
      question: 'Can I start with less than ₹10k?',
      answer:
        'Yes! Using a Step-Up SIP of 10% annually, you can start with as little as ₹5,500/month and still reach ₹1 Crore in 20 years as your income grows.',
    },
    {
      question: 'Is it safe to invest in equity for 20 years?',
      answer:
        'Yes. While equity is volatile in the short term (1-3 years), historically, over any 15-20 year period in India, diversified equity indices have never given negative returns.',
    },
  ];

  return (
    <article className="mx-auto max-w-5xl px-4 py-6 sm:px-6 lg:px-8">
      {/* --- BREADCRUMBS --- */}
      <BreadcrumbJsonLd
        items={[
          { name: 'Guides', url: 'https://www.fincado.com/guides' },
          {
            name: '1 Crore in 20 Years',
            url: 'https://www.fincado.com/guides/sip-for-1-crore-in-20-years',
          },
        ]}
      />

      {/* --- FAQ SCHEMA --- */}
      <FAQSchema faqs={faqData} />

      {/* --- ARTICLE SCHEMA --- */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'Article',
            inLanguage: 'en-IN',
            headline: pageTitle,
            description:
              'Detailed calculation and strategy to build a corpus of ₹1 Crore in 20 years using Mutual Funds.',
            author: {
              '@type': 'Person',
              name: 'Fincado Research Team',
            },
            publisher: {
              '@type': 'Organization',
              name: 'Fincado',
              logo: {
                '@type': 'ImageObject',
                url: 'https://www.fincado.com/logo.png',
              },
            },
            datePublished: '2025-12-28',
            dateModified: '2025-12-28',
            image:
              'https://www.fincado.com/images/guides/mf/mutual-fund-guide-hero.webp',
          }),
        }}
      />

      {/* --- HEADER --- */}
      <header className="mb-8 border-b border-slate-200 pb-6 no-print">
        <Badge
          variant="secondary"
          className="mb-3 bg-emerald-100 text-emerald-800 hover:bg-emerald-200 px-3 py-1"
        >
          Wealth Strategy
        </Badge>
        <h1 className="text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl md:text-5xl leading-tight">
          {pageTitle}
        </h1>
        <div className="mt-4 flex flex-wrap items-center gap-4 text-sm text-slate-500">
          <span className="flex items-center gap-1">
            <Clock className="h-4 w-4" /> 5 Min Read
          </span>
          <span className="hidden sm:inline">•</span>
          <span>
            Updated: <strong className="text-slate-700">Dec 2025</strong>
          </span>
          <span className="hidden sm:inline">•</span>
          <span className="flex items-center gap-1 font-medium text-emerald-600">
            <TrendingUp className="h-4 w-4" /> Calculated @ 12% CAGR
          </span>
        </div>
        <div className="mt-6">
          <ShareTools title={pageTitle} />
        </div>
      </header>

      {/* --- INTRO CARD --- */}
      <Card className="mb-10 border-slate-200 bg-white shadow-sm">
        <CardContent className="pt-6 text-slate-700 leading-relaxed text-lg">
          <div className="my-6 relative h-64 w-full sm:h-80 md:h-96 bg-slate-100 rounded-lg overflow-hidden border border-slate-100">
            <Image
              src="/images/guides/mf/mutual-fund-guide-hero.webp"
              alt="Roadmap to 1 Crore Wealth"
              fill
              priority
              className="object-cover"
            />
          </div>
          <WikiText
            content={`<p>Becoming a Crorepati in 20 years is mathematically easy for almost anyone who starts early. Unlike shorter timelines where you have to invest heavily, in a 20-year horizon, the <strong>power of compounding</strong> does 75% of the heavy lifting for you.</p>`}
          />
          <p className="text-sm text-slate-500 italic text-center mt-4">
            <strong>Updated for 2025:</strong> All calculations use current
            market return assumptions.
          </p>
        </CardContent>
      </Card>

      {/* --- SECTION 1: THE ANSWER --- */}
      <Card className="mb-12 bg-emerald-50 border-emerald-200 shadow-md">
        <CardHeader className="pb-2">
          <CardTitle className="text-emerald-900 text-xl flex items-center gap-2">
            <Target className="h-6 w-6 text-emerald-700" /> The Short Answer
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-emerald-800 text-lg mb-6">
            To reach <strong>₹1 Crore in 20 Years</strong>, assuming a 12%
            annual return from equity mutual funds, you need to start a monthly
            SIP of roughly <span className="font-bold text-2xl">₹10,009</span>.
          </p>
          <div className="bg-white p-6 rounded-lg shadow-sm mb-6 border border-emerald-100">
            <InlineSipCalculator
              defaultSip={10009}
              defaultYears={20}
              defaultRate={12}
            />
          </div>
          <div className="flex justify-end">
            <Link
              href="/sip-calculator"
              className="inline-flex items-center text-sm font-medium text-emerald-700 hover:text-emerald-800 hover:underline"
            >
              Check Your Own Goal <ArrowRight className="h-4 w-4 ml-1" />
            </Link>
          </div>
        </CardContent>
      </Card>

      {/* 💰 AD SLOT 1 */}
      <div className="no-print my-8">
        <AdSlot id="guide-1cr-1" type="leaderboard" />
      </div>

      {/* --- SECTION 2: THE MATH --- */}
      <section className="mb-12">
        <h2
          id="the-math"
          className="mb-6 text-2xl font-bold text-slate-900 scroll-mt-20 flex items-center gap-2"
        >
          <Calculator className="h-6 w-6 text-blue-600" /> The Math: Wealth on
          Autopilot
        </h2>
        <p className="mb-6 text-slate-700">
          In a 20-year journey, you barely invest a quarter of the final amount.
          The market earns the rest. This is the ultimate &quot;Wealth on
          Autopilot&quot; strategy.
        </p>

        {/* IMAGE: Compounding Graph */}
        <div className="mb-8 overflow-hidden rounded-xl bg-slate-50 border border-slate-200 flex justify-center shadow-sm">
          <Image
            src="/images/guides/sip/power-of-compounding-graph.webp"
            alt="Graph showing power of compounding over time"
            width={800}
            height={400}
            className="rounded-lg w-full h-auto object-contain"
          />
        </div>

        <div className="overflow-hidden rounded-lg border border-slate-200 mb-6 shadow-sm">
          <Table>
            <TableHeader>
              <TableRow className="bg-slate-100 hover:bg-slate-100">
                <TableHead className="font-bold text-slate-900">
                  Parameter
                </TableHead>
                <TableHead className="font-bold text-slate-900">
                  Value
                </TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>Target Amount</TableCell>
                <TableCell className="font-bold text-slate-900">
                  ₹1,00,00,000 (1 Crore)
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Time Period</TableCell>
                <TableCell>20 Years (240 Months)</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Expected Return</TableCell>
                <TableCell className="text-emerald-600 font-bold">
                  12% (Equity Benchmark)
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Monthly SIP</TableCell>
                <TableCell className="text-blue-600 font-bold text-lg">
                  ₹10,009
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Total Invested</TableCell>
                <TableCell>₹24.0 Lakhs</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Wealth Gained</TableCell>
                <TableCell className="text-emerald-600 font-bold">
                  ₹76.0 Lakhs (76% Free Money!)
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </section>

      {/* --- SECTION 3: TIME COMPARISON --- */}
      <section className="mb-12">
        <h2
          id="time-comparison"
          className="mb-6 text-2xl font-bold text-slate-900 scroll-mt-20 flex items-center gap-2"
        >
          <Clock className="h-6 w-6 text-amber-500" /> Comparison with Other
          Timelines
        </h2>
        <div className="overflow-hidden rounded-lg border border-slate-200 mb-6 shadow-sm">
          <Table>
            <TableHeader>
              <TableRow className="bg-slate-100 hover:bg-slate-100">
                <TableHead className="font-bold text-slate-900">Time</TableHead>
                <TableHead className="font-bold text-slate-900">
                  SIP Needed
                </TableHead>
                <TableHead className="font-bold text-slate-900">
                  Total Invested
                </TableHead>
                <TableHead className="font-bold text-slate-900">Ease</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>10 Years</TableCell>
                <TableCell>₹43,041</TableCell>
                <TableCell>₹51.6 L</TableCell>
                <TableCell className="text-red-600 font-medium">Hard</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>15 Years</TableCell>
                <TableCell>₹19,819</TableCell>
                <TableCell>₹35.6 L</TableCell>
                <TableCell className="text-emerald-600 font-medium">
                  Moderate
                </TableCell>
              </TableRow>
              <TableRow className="bg-emerald-50/50">
                <TableCell className="font-bold text-emerald-900">
                  20 Years
                </TableCell>
                <TableCell className="font-bold text-emerald-900">
                  ₹10,009
                </TableCell>
                <TableCell className="text-emerald-900">₹24.0 L</TableCell>
                <TableCell className="text-emerald-700 font-bold">
                  Easy (Autopilot)
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell>25 Years</TableCell>
                <TableCell>₹5,270</TableCell>
                <TableCell>₹15.8 L</TableCell>
                <TableCell className="text-emerald-600 font-medium">
                  Very Easy
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>

        <div className="flex flex-wrap gap-4 mt-4">
          <Link
            href="/guides/sip-for-1-crore-in-10-years"
            className="text-sm font-medium text-blue-600 hover:underline flex items-center"
          >
            Want it faster? See 10-Year Plan{' '}
            <ArrowRight className="h-4 w-4 ml-1" />
          </Link>
          <Link
            href="/guides/sip-for-1-crore-in-15-years"
            className="text-sm font-medium text-blue-600 hover:underline flex items-center"
          >
            Want it balanced? See 15-Year Plan{' '}
            <ArrowRight className="h-4 w-4 ml-1" />
          </Link>
        </div>
      </section>

      {/* 💰 AD SLOT 2 */}
      <div className="no-print my-8">
        <AdSlot id="guide-1cr-2" type="leaderboard" />
      </div>

      {/* --- SECTION 4: STEP UP STRATEGY --- */}
      <section className="mb-12">
        <h2
          id="step-up-strategy"
          className="mb-6 text-2xl font-bold text-slate-900 scroll-mt-20 flex items-center gap-2"
        >
          <TrendingUp className="h-6 w-6 text-purple-600" /> The &quot;Start
          Small&ldquo; Strategy
        </h2>
        <p className="mb-6 text-slate-700">
          Even if you can&#39;t afford ₹10k today, start with ₹5.5k and step up
          by 10% annually.
        </p>

        {/* IMAGE: Step Up Strategy */}
        <div className="mb-8 overflow-hidden rounded-xl bg-slate-50 border border-slate-200 flex justify-center shadow-sm">
          <Image
            src="/images/guides/sip/step-up-strategy.webp"
            alt="Visualizing Step-Up SIP Strategy"
            width={800}
            height={400}
            className="rounded-lg w-full h-auto object-contain"
          />
        </div>

        <Card className="border-purple-100 bg-purple-50/30 mb-6">
          <CardHeader className="pb-2 border-b border-purple-100">
            <CardTitle className="text-purple-900 text-lg flex items-center gap-2">
              <Zap className="h-5 w-5" /> The Plan (Start Very Small)
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4 text-sm text-slate-700">
            <ul className="space-y-3">
              <li className="flex justify-between items-center">
                <span>Starting SIP:</span>
                <strong className="text-base">₹5,500 / month</strong>
              </li>
              <li className="flex justify-between items-center">
                <span>Annual Increase:</span>
                <strong className="text-base">10%</strong>
              </li>
              <li className="flex justify-between items-center pt-2 border-t border-purple-200">
                <span className="font-bold text-purple-800">
                  Result (20 Yrs):
                </span>
                <span className="font-bold text-purple-800 text-lg">
                  ₹1.02 Crore ✅
                </span>
              </li>
            </ul>
          </CardContent>
        </Card>

        <div className="overflow-hidden rounded-lg border border-slate-200 shadow-sm">
          <Table>
            <TableHeader>
              <TableRow className="bg-slate-100 hover:bg-slate-100">
                <TableHead className="font-bold text-slate-900">Year</TableHead>
                <TableHead className="font-bold text-slate-900">
                  Monthly SIP
                </TableHead>
                <TableHead className="font-bold text-slate-900">
                  Corpus (Year End)
                </TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>Year 1</TableCell>
                <TableCell>₹5,500</TableCell>
                <TableCell>₹70k</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Year 5</TableCell>
                <TableCell>₹8,050</TableCell>
                <TableCell>₹5.6 L</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Year 10</TableCell>
                <TableCell>₹12,900</TableCell>
                <TableCell>₹19.2 L</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>Year 15</TableCell>
                <TableCell>₹20,800</TableCell>
                <TableCell>₹49.8 L</TableCell>
              </TableRow>
              <TableRow className="bg-emerald-50">
                <TableCell className="font-bold text-emerald-900">
                  Year 20
                </TableCell>
                <TableCell className="font-bold text-emerald-900">
                  ₹33,600
                </TableCell>
                <TableCell className="font-bold text-emerald-700">
                  ₹1.02 Cr
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </section>

      {/* --- SECTION 5: ASSET ALLOCATION --- */}
      <section className="mb-12">
        <h2
          id="where-to-invest"
          className="mb-6 text-2xl font-bold text-slate-900 scroll-mt-20 flex items-center gap-2"
        >
          <PieChart className="h-6 w-6 text-teal-600" /> Where Should You
          Invest?
        </h2>
        <p className="mb-6 text-slate-700">
          For a 20-year horizon, risk is naturally mitigated by time. Equity is
          the only asset class that consistently beats inflation over two
          decades.
        </p>

        <div className="grid gap-6 md:grid-cols-2">
          <Card className="border-l-4 border-l-emerald-500 shadow-sm h-full">
            <CardHeader className="pb-2">
              <CardTitle className="text-emerald-800 text-lg">
                Balanced (Recommended)
              </CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-slate-700">
              <p className="mb-2 font-bold text-emerald-600">Aim: 12% Return</p>
              <ul className="list-disc pl-4 space-y-1 mb-4">
                <li>50% Nifty 50 Index Fund</li>
                <li>30% Flexi Cap Fund</li>
                <li>20% Mid Cap Fund</li>
              </ul>
              <p className="text-xs italic text-slate-500">
                Risk: Low/Moderate over 20 years. Ideal for &#34;Fill it, Shut
                it, Forget it&ldquo;.
              </p>
            </CardContent>
          </Card>

          <Card className="border-l-4 border-l-red-500 shadow-sm h-full">
            <CardHeader className="pb-2">
              <CardTitle className="text-red-800 text-lg">Aggressive</CardTitle>
            </CardHeader>
            <CardContent className="text-sm text-slate-700">
              <p className="mb-2 font-bold text-red-600">Aim: 14-15% Return</p>
              <ul className="list-disc pl-4 space-y-1 mb-4">
                <li>40% Mid Cap Funds</li>
                <li>40% Small Cap Funds</li>
                <li>20% Flexi Cap Funds</li>
              </ul>
              <p className="text-xs italic text-slate-500">
                Risk: High volatility, but potential to reach 1Cr in 15-17
                years.
              </p>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* 💰 AD SLOT 3 */}
      <div className="no-print my-8">
        <AdSlot id="guide-1cr-3" type="leaderboard" />
      </div>

      {/* --- SECTION 6: MISTAKES --- */}
      <section className="mb-12">
        <h2
          id="common-mistakes"
          className="mb-6 text-2xl font-bold text-slate-900 scroll-mt-20 flex items-center gap-2"
        >
          <AlertTriangle className="h-6 w-6 text-red-500" /> Mistakes That Kill
          the Dream
        </h2>
        <div className="grid gap-4 sm:grid-cols-3">
          <Card className="bg-red-50 border-red-100">
            <CardContent className="p-4">
              <strong className="block text-red-900 mb-2">
                1. Stopping SIP
              </strong>
              <p className="text-sm text-red-800">
                In 20 years, market will crash 3-4 times. Stopping SIP destroys
                compounding.
              </p>
            </CardContent>
          </Card>
          <Card className="bg-red-50 border-red-100">
            <CardContent className="p-4">
              <strong className="block text-red-900 mb-2">
                2. Ignoring Inflation
              </strong>
              <p className="text-sm text-red-800">
                ₹1 Cr in 20 years = ~₹30L today. Aim for ₹2-3 Cr if possible.
              </p>
            </CardContent>
          </Card>
          <Card className="bg-red-50 border-red-100">
            <CardContent className="p-4">
              <strong className="block text-red-900 mb-2">
                3. Delaying Start
              </strong>
              <p className="text-sm text-red-800">
                Waiting 5 years doubles your required SIP to ~₹19k. Start now.
              </p>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* --- FAQS --- */}
      <section className="mb-12">
        <h2
          id="faqs"
          className="mb-6 text-2xl font-bold text-slate-900 scroll-mt-20"
        >
          Frequently Asked Questions
        </h2>
        <Accordion type="single" collapsible className="w-full space-y-2">
          {faqData.map((faq, index) => (
            <AccordionItem
              key={index}
              value={`item-${index}`}
              className="border rounded-lg px-4 bg-white"
            >
              <AccordionTrigger className="text-left text-slate-900 font-semibold hover:no-underline">
                {faq.question}
              </AccordionTrigger>
              <AccordionContent className="text-slate-700 text-base leading-relaxed">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </section>

      {/* --- CONCLUSION --- */}
      <Card className="mb-8 border-slate-200 bg-slate-900 text-white">
        <CardContent className="p-8">
          <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
            <Lightbulb className="h-6 w-6 text-yellow-400" /> Final Verdict
          </h2>
          <p className="mb-6 text-slate-300 leading-relaxed">
            Reaching ₹1 Crore in 20 years is the easiest path to wealth. It
            requires a small SIP of ₹10,000 (or just ₹5,500 with step-ups). The
            most important factor is to <strong>start immediately</strong>.
          </p>
          <div className="flex flex-wrap gap-4">
            <div className="flex items-center gap-2 text-sm bg-slate-800 px-3 py-1 rounded-full border border-slate-700">
              <CheckCircle2 className="h-4 w-4 text-emerald-400" /> Start Small
            </div>
            <div className="flex items-center gap-2 text-sm bg-slate-800 px-3 py-1 rounded-full border border-slate-700">
              <CheckCircle2 className="h-4 w-4 text-emerald-400" /> Step Up 10%
            </div>
            <div className="flex items-center gap-2 text-sm bg-slate-800 px-3 py-1 rounded-full border border-slate-700">
              <CheckCircle2 className="h-4 w-4 text-emerald-400" /> Be Patient
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="mb-8 border-t border-slate-200 pt-8">
        <AuthorBio />
      </div>

      {/* --- FINAL CTA --- */}
      <Card className="bg-linear-to-br from-emerald-600 to-teal-700 text-white border-none shadow-xl no-print">
        <CardContent className="flex flex-col items-center p-8 text-center sm:p-12">
          <h2 className="mb-4 text-2xl font-bold sm:text-3xl">
            Calculate Your Own Path to 1 Crore
          </h2>
          <p className="mb-8 max-w-lg text-emerald-100 text-lg">
            Want to see how much YOU need to save based on your current age? Use
            our free calculator to customize the numbers.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <Link
              href="/sip-calculator"
              className="rounded-lg bg-white px-8 py-4 font-bold text-emerald-700 transition hover:bg-emerald-50 shadow-lg"
            >
              Open SIP Calculator
            </Link>
            <Link
              href="/mutual-funds"
              className="rounded-lg border border-emerald-400 bg-emerald-800/30 px-8 py-4 font-bold text-white transition hover:bg-emerald-800/50"
            >
              See Top Funds
            </Link>
          </div>
        </CardContent>
      </Card>
    </article>
  );
}
