import type { Metadata } from 'next';
import React from 'react';
import Link from 'next/link';
import SWPClient from './SWPClient';
import FinancialNavWidget from '@/components/FinancialNavWidget';
import AdSlot from '@/components/AdSlot';
import AuthorBio from '@/components/AuthorBio';
import WikiText from '@/components/WikiText';
import BreadcrumbJsonLd from '@/components/BreadcrumbJsonLd';
import CalculatorSchema from '@/components/CalculatorSchema';
import ShareTools from '@/components/ShareTools';
import LanguageToggle from '@/components/LanguageToggle';
import 'katex/dist/katex.min.css';
import { BlockMath } from 'react-katex';
import { autoLinkContent } from '@/utils/autoLinker';
import { Card, CardContent } from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import FAQSchema from '@/components/FAQSchema';

/* ---------------- SEO METADATA ---------------- */
export const metadata: Metadata = {
  title: 'SWP Calculator 2026 – Monthly Pension from Mutual Funds',
  description:
    'Calculate monthly income from Mutual Fund investments. Estimate corpus longevity, 2025 tax rules (LTCG), and compare SWP vs Dividend plans.',
  keywords: [
    'SWP Calculator',
    'Systematic Withdrawal Plan',
    'Monthly Income Plan',
    'Mutual Fund SWP vs Dividend',
    'Retirement Income Calculator',
    'SWP Tax Calculation 2026',
  ],
  alternates: {
    canonical: 'https://fincado.com/swp-calculator/',
  },
  openGraph: {
    title: 'SWP Calculator – Regular Income Generator',
    description:
      'Free tool to plan your monthly withdrawals from mutual fund investments.',
    url: 'https://fincado.com/swp-calculator/',
    type: 'website',
  },
};

// swpFaqs.ts (or inside the page file)

export const SWP_FAQS = [
  {
    question: 'Can my SWP corpus become zero?',
    answer:
      'Yes. If your monthly withdrawal is higher than the returns generated by the fund, you will start eating into your principal. Over time, this can fully deplete the corpus.',
  },
  {
    question: 'Is SWP taxable?',
    answer:
      'Yes, but it is tax-efficient. Each withdrawal contains principal (not taxed) and capital gains (taxed). For equity funds held over 1 year, long-term capital gains above ₹1.25 lakh are taxed at applicable LTCG rates as per current tax laws.',
  },
  {
    question: 'Can I stop my SWP anytime?',
    answer:
      'Yes. SWP is completely flexible. You can stop, pause, or modify the withdrawal amount at any time without penalties from the mutual fund house.',
  },
];

/* ---------------- PAGE ---------------- */

export default function SWPPage() {
  const introContent = autoLinkContent(`
    <p>
      A <strong>Systematic Withdrawal Plan (SWP)</strong> allows investors to withdraw a specific 
      sum of money from their <strong>Mutual Fund</strong> investments at regular intervals 
      (monthly, quarterly, or annually).
    </p>
    <p class="mt-2">
      It is essentially the reverse of an <strong>SIP</strong>. While SIP is for wealth accumulation, 
      SWP is for wealth distribution, making it the gold standard for retirees looking for a 
      regular "pension-like" income from their corpus.
    </p>
  `);

  const taxContent = autoLinkContent(`
    <p>
      SWP is highly tax-efficient because you are not taxed on the entire withdrawal amount—only on 
      the <strong>Capital Gains</strong> portion of it.
    </p>
    <ul class="list-disc pl-5 space-y-2 mt-2">
      <li><strong>Equity Funds (LTCG):</strong> If held for >1 year, gains above ₹1.25 Lakh/year are taxed at <strong>12.5%</strong>.</li>
      <li><strong>Debt Funds:</strong> Taxed as per your income tax slab (no indexation benefit for fresh investments after April 2023).</li>
    </ul>
  `);

  const safeWithdrawalContent = autoLinkContent(`
    <p>
      Financial planners often cite the <strong>"4% Rule"</strong>. It suggests that if you withdraw 
      <strong>4%</strong> of your retirement corpus annually (adjusted for inflation), your money 
      should last for 30 years or more without depleting completely.
    </p>
  `);

  return (
    <>
      <CalculatorSchema
        name="SWP Calculator"
        description="Plan your systematic withdrawals from mutual funds. Calculate how long your corpus will last with monthly payouts."
        url="https://fincado.com/swp-calculator/"
      />

      <FAQSchema
        faqs={SWP_FAQS.map((faq) => ({
          question: faq.question,
          answer: faq.answer,
        }))}
      />

      <main className="container" style={{ padding: '40px 20px' }}>
        <BreadcrumbJsonLd
          items={[
            { name: 'Home', url: 'https://fincado.com/' },
            { name: 'Calculators', url: 'https://fincado.com/calculators/' },
            {
              name: 'SWP Calculator',
              url: 'https://fincado.com/swp-calculator/',
            },
          ]}
        />

        <header className="no-print my-4">
          {/* Share + Language */}
          <div className="no-print mb-6 flex items-center justify-between gap-4">
            <ShareTools title="SWP Calculator — Systematic Withdrawal Plan" />
            <LanguageToggle path="/hi/swp-calculator" />
          </div>

          {/* Title */}
          <h1
            className="
      text-[clamp(1.9rem,4vw,2.6rem)]
      font-semibold
      leading-tight
      tracking-[-0.02em]
      text-slate-900
    "
          >
            <span
              className="
        block
        text-2xl
        sm:text-3xl
        lg:text-4xl
        font-semibold
        tracking-tight
      "
            >
              SWP Calculator
            </span>

            <span className="block mt-2 text-base sm:text-lg font-medium text-lime-700">
              Generate regular income from your investment corpus
            </span>
          </h1>

          {/* Intro */}
          <WikiText
            content={`
      <p class="max-w-175 text-slate-600 mt-2">
        Turn your investments into a steady monthly salary.
        Calculate how much you can withdraw every month and
        see how long your retirement corpus will last.
      </p>
    `}
          />
        </header>

        <div className="layout-grid">
          <div className="main-content">
            <SWPClient />

            {/* 💰 AD 2: AFTER CALCULATOR */}
            <div className="no-print my-8">
              <AdSlot id="swp-after-calc" type="banner" />
            </div>

            {/* 📱 Mobile-only Related Tools */}
            <div className="mobile-only-suggestions my-8">
              <h3 className="text-lg font-semibold text-slate-900 mb-4">
                Retirement Tools
              </h3>

              <div className="grid grid-cols-2 gap-3">
                <Link
                  href="/sip-calculator/"
                  className="
        flex items-center justify-center
        rounded-lg border border-slate-200
        bg-white px-3 py-3
        text-sm font-medium text-slate-900
        hover:border-lime-300 hover:bg-lime-50
        transition
      "
                >
                  📈 SIP Calculator
                </Link>

                <Link
                  href="/fd-calculator/"
                  className="
        flex items-center justify-center
        rounded-lg border border-slate-200
        bg-white px-3 py-3
        text-sm font-medium text-slate-900
        hover:border-lime-300 hover:bg-lime-50
        transition
      "
                >
                  🏦 FD Calculator
                </Link>
              </div>
            </div>

            {/* 🟢 Promo Box */}
            <div className="no-print my-8">
              <div
                className="
      flex items-center gap-3
      rounded-lg border border-lime-200
      bg-lime-50
      px-4 py-4
    "
              >
                <span className="text-2xl">👴</span>

                <div>
                  <strong className="block text-sm font-semibold text-lime-900">
                    Retired or Retiring soon?
                  </strong>

                  <Link
                    href="/guides/swp-guide/"
                    className="
          mt-1 inline-block
          text-sm font-semibold text-lime-700
          underline underline-offset-2
          hover:text-lime-800
        "
                  >
                    Read: How to create a Tax-Free Pension →
                  </Link>
                </div>
              </div>
            </div>

            {/* --- FULL SEO ARTICLE --- */}
            <article className="article content-for-seo no-print space-y-10">
              {/* INTRO */}
              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-slate-900">
                  What is a Systematic Withdrawal Plan (SWP)?
                </h2>
                <WikiText content={introContent} />
              </section>

              {/* COMPARISON */}
              <section className="space-y-6">
                <h3 className="text-xl font-semibold text-slate-900">
                  SWP vs Dividend (IDCW): Which is Better?
                </h3>

                <Card>
                  <CardContent>
                    <div className="overflow-x-auto">
                      <Table className="border-collapse">
                        <TableHeader>
                          <TableRow>
                            <TableHead>Feature</TableHead>
                            <TableHead>SWP (Growth Option)</TableHead>
                            <TableHead>Dividend (IDCW)</TableHead>
                          </TableRow>
                        </TableHeader>

                        <TableBody>
                          <TableRow>
                            <TableCell className="font-medium text-slate-700">
                              Payout Amount
                            </TableCell>
                            <TableCell className="font-semibold text-emerald-600">
                              Fixed (You decide)
                            </TableCell>
                            <TableCell className="text-slate-700">
                              Uncertain (AMC decides)
                            </TableCell>
                          </TableRow>

                          <TableRow>
                            <TableCell className="font-medium text-slate-700">
                              Taxation
                            </TableCell>
                            <TableCell className="font-semibold text-emerald-600">
                              Capital Gains (Lower)
                            </TableCell>
                            <TableCell className="text-red-600 font-semibold">
                              Slab Rate (Higher)
                            </TableCell>
                          </TableRow>

                          <TableRow>
                            <TableCell className="font-medium text-slate-700">
                              Control
                            </TableCell>
                            <TableCell className="font-semibold text-emerald-600">
                              Full Control
                            </TableCell>
                            <TableCell className="text-slate-700">
                              No Control
                            </TableCell>
                          </TableRow>

                          <TableRow>
                            <TableCell className="font-medium text-slate-700">
                              Best For
                            </TableCell>
                            <TableCell className="text-slate-700">
                              Monthly Income
                            </TableCell>
                            <TableCell className="text-slate-700">
                              Occasional Payouts
                            </TableCell>
                          </TableRow>
                        </TableBody>
                      </Table>
                    </div>
                  </CardContent>
                </Card>
              </section>

              {/* AD */}
              <div className="no-print my-8 flex justify-center">
                <AdSlot type="square" label="Advertisement" />
              </div>

              {/* TAX */}
              <section className="space-y-4">
                <h3 className="text-xl font-semibold text-slate-900">
                  Taxation on SWP (2026 Rules)
                </h3>
                <WikiText content={taxContent} />
              </section>

              {/* SAFE WITHDRAWAL */}
              <section className="space-y-4">
                <h3 className="text-xl font-semibold text-slate-900">
                  How Long Will My Money Last? (Safe Withdrawal Rate)
                </h3>
                <WikiText content={safeWithdrawalContent} />
              </section>

              {/* ADVANTAGES */}
              <section className="space-y-6">
                <h3 className="text-xl font-semibold text-slate-900">
                  How This Calculator Helps Your Planning
                </h3>

                <div className="advantage-grid">
                  <div className="advantage-card">
                    <h4>Corpus Longevity</h4>
                    <p>
                      See exactly how many years your corpus will last with a
                      fixed monthly withdrawal.
                    </p>
                  </div>

                  <div className="advantage-card">
                    <h4>Capital Protection</h4>
                    <p>
                      Understand whether withdrawals are eating into your
                      principal or still allowing growth.
                    </p>
                  </div>

                  <div className="advantage-card">
                    <h4>Inflation Awareness</h4>
                    <p>
                      A fixed withdrawal loses purchasing power over time—plan
                      smarter.
                    </p>
                  </div>
                </div>
              </section>

              {/* FORMULA */}
              <section className="space-y-4">
                <h3 className="text-xl font-semibold text-slate-900">
                  SWP Calculation Logic
                </h3>

                <p>
                  The remaining balance after systematic withdrawals is
                  calculated using the annuity withdrawal formula:
                </p>

                <div className="py-6 overflow-x-auto bg-slate-50 px-4 rounded-md">
                  <BlockMath math="Bal = P(1+i)^n - W \times \frac{(1+i)^n - 1}{i}" />
                </div>

                <WikiText
                  content={`
        <ul class="list-disc pl-5 text-sm">
          <li><strong>Bal</strong>: Final Balance</li>
          <li><strong>P</strong>: Initial Investment</li>
          <li><strong>W</strong>: Monthly Withdrawal</li>
          <li><strong>i</strong>: Monthly Return Rate</li>
          <li><strong>n</strong>: Total Months</li>
        </ul>
      `}
                />
              </section>

              {/* KEY ADVANTAGES */}
              <section className="space-y-4">
                <h3 className="text-xl font-semibold text-slate-900">
                  Key Advantages of SWP
                </h3>

                <WikiText
                  content={`
        <ul class="list-disc pl-5 space-y-2">
          <li><strong>Tax Efficient:</strong> Capital gains tax is lower than FD interest.</li>
          <li><strong>Flexible:</strong> Pause, stop, or change withdrawals anytime.</li>
          <li><strong>Cost Averaging:</strong> Units are sold gradually over market cycles.</li>
        </ul>
      `}
                />
              </section>
            </article>

            {/* --- FAQs --- */}
            <section className="article no-print mt-12">
              <h2 className="text-2xl font-semibold text-slate-900 mb-6">
                Frequently Asked Questions (FAQs)
              </h2>

              <Accordion type="single" collapsible className="w-full">
                {SWP_FAQS.map((faq, idx) => (
                  <AccordionItem key={idx} value={`swp-faq-${idx}`}>
                    <AccordionTrigger className="text-left text-slate-900 font-medium">
                      {faq.question}
                    </AccordionTrigger>
                    <AccordionContent className="text-slate-600 leading-relaxed">
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </section>

            <AuthorBio />
          </div>

          <aside className="sidebar no-print">
            <div className="sticky top-5 mb-6">
              <AdSlot id="swp-sidebar" type="box" />
            </div>

            <FinancialNavWidget />
          </aside>
        </div>
      </main>
    </>
  );
}
